const indianVeg = [
  'Paneer Butter Masala',
  'Paneer Tikka',
  'Kadai Paneer',
  'Palak Paneer',
  'Shahi Paneer',
  'Paneer Lababdar',
  'Paneer Do Pyaza',
  'Paneer Bhurji',
  'Matar Paneer',
  'Malai Kofta',
  'Veg Kofta',
  'Dal Tadka',
  'Dal Fry',
  'Dal Makhani',
  'Chana Masala',
  'Rajma Masala',
  'Aloo Gobi',
  'Aloo Matar',
  'Dum Aloo',
  'Jeera Aloo',
  'Bhindi Masala',
  'Baingan Bharta',
  'Mushroom Masala',
  'Mushroom Tikka',
  'Veg Jalfrezi',
  'Veg Kolhapuri',
  'Mix Veg Curry',
  'Veg Handi',
  'Veg Korma',
  'Gobi Manchurian',
  'Chilli Paneer',
  'Veg Manchurian',
  'Hakka Noodles',
  'Veg Fried Rice',
  'Schezwan Fried Rice',
  'Veg Biryani',
  'Hyderabadi Veg Biryani',
  'Pulao',
  'Jeera Rice',
  'Curd Rice',
  'Lemon Rice',
  'Idli',
  'Medu Vada',
  'Masala Dosa',
  'Plain Dosa',
  'Rava Dosa',
  'Uttapam',
  'Pav Bhaji',
  'Chole Bhature',
  'Samosa',
  'Kachori',
  'Dhokla',
  'Poha',
  'Upma',
  'Pani Puri',
  'Sev Puri',
  'Bhel Puri',
  'Aloo Tikki',
  'Veg Momos',
  'Spring Roll',
  'Tandoori Roti',
  'Butter Naan',
  'Garlic Naan',
  'Lachha Paratha',
  'Aloo Paratha',
  'Gobi Paratha',
  'Paneer Paratha',
  'Green Salad',
  'Russian Salad',
  'Masala Papad',
  'Raita',
  'Boondi Raita',
  'Dahi Vada',
];

const indianNonVeg = [
  'Chicken Biryani',
  'Mutton Biryani',
  'Egg Biryani',
  'Chicken Tikka',
  'Chicken Malai Tikka',
  'Tandoori Chicken',
  'Butter Chicken',
  'Chicken Curry',
  'Chicken Korma',
  'Chicken Chettinad',
  'Chicken Kolhapuri',
  'Chicken Do Pyaza',
  'Chicken Lababdar',
  'Kadai Chicken',
  'Chicken Handi',
  'Chicken Lollipop',
  'Chilli Chicken',
  'Chicken Manchurian',
  'Chicken Fried Rice',
  'Chicken Hakka Noodles',
  'Mutton Rogan Josh',
  'Mutton Curry',
  'Mutton Korma',
  'Mutton Keema',
  'Mutton Seekh Kebab',
  'Galouti Kebab',
  'Fish Curry',
  'Fish Fry',
  'Fish Tikka',
  'Prawn Curry',
  'Prawn Masala',
  'Prawn Fry',
  'Egg Curry',
  'Egg Bhurji',
  'Omelette',
  'Chicken Shawarma',
  'Chicken Momos',
  'Mutton Momos',
  'Chicken Burger',
  'Fish Burger',
  'Chicken Sandwich',
  'Chicken Pizza',
  'Pepperoni Pizza',
  'Sausage Pizza',
  'Chicken Wings',
  'Grilled Chicken',
  'Chicken Popcorn',
  'Chicken Nuggets',
  'Fish Fingers',
  'Prawn Tempura',
  'Chicken Kebab',
  'Reshmi Kebab',
  'Tangdi Kebab',
  'Afghani Chicken',
  'Chicken 65',
  'Mutton Pepper Fry',
  'Mutton Chops',
  'Crab Masala',
  'Seafood Platter',
  'Egg Fried Rice',
];

const fastFoodVeg = [
  'Margherita Pizza',
  'Farmhouse Pizza',
  'Veggie Delight Pizza',
  'Cheese Burst Pizza',
  'Corn Cheese Pizza',
  'Paneer Pizza',
  'Veg Burger',
  'Cheese Burger',
  'Aloo Tikki Burger',
  'Veg Sandwich',
  'Cheese Sandwich',
  'Club Sandwich',
  'French Fries',
  'Peri Peri Fries',
  'Cheese Fries',
  'Nachos',
  'Cheese Nachos',
  'Garlic Bread',
  'Stuffed Garlic Bread',
  'Veg Pasta',
  'White Sauce Pasta',
  'Red Sauce Pasta',
  'Mac and Cheese',
  'Veg Wrap',
  'Paneer Wrap',
  'Falafel Wrap',
  'Veg Taco',
  'Bean Burrito',
  'Cheese Quesadilla',
  'Veg Sub',
  'Corn Chaat',
  'Loaded Potato',
  'Onion Rings',
  'Mozzarella Sticks',
  'Veg Cutlet',
  'Veg Roll',
  'Paneer Roll',
  'Cheese Maggi',
  'Masala Maggi',
  'Veg Thali',
];

const drinks = [
  'Coke',
  'Diet Coke',
  'Coca Cola',
  'Coca-Cola',
  'Coca-Cola Zero Sugar',
  'Coke Zero',
  'Coke Zero Sugar',
  'Pepsi',
  'Diet Pepsi',
  'Pepsi Black',
  'Sprite',
  'Sprite Zero Sugar',
  'Fanta',
  'Fanta Orange',
  'Thums Up',
  'Thums Up Charged',
  'Limca',
  'Limca Sportz',
  'Mountain Dew',
  '7 Up',
  'Seven Up',
  'Mirinda',
  'Mirinda Orange',
  'Slice',
  'Tropicana',
  'Tropicana Juice',
  'Tropicana Orange',
  'Tropicana Apple',
  'Tropicana Guava',
  'Aquafina',
  'Sting',
  'Sting Energy',
  'Gatorade',
  'Gatorade Blue Bolt',
  'Gatorade Orange',
  'Lipton Ice Tea',
  'Lipton Lemon Iced Tea',
  'Lipton Peach Iced Tea',
  'Maaza',
  'Maaza Mango',
  'Maaza Aam Panna',
  'Minute Maid',
  'Minute Maid Pulpy Orange',
  'Minute Maid Apple',
  'Minute Maid Guava',
  'Minute Maid Mixed Fruit',
  'Minute Maid Vita Punch',
  'Kinley',
  'Kinley Water',
  'Kinley Soda',
  'Schweppes',
  'Schweppes Tonic Water',
  'Schweppes Ginger Ale',
  'Campa Cola',
  'Campa Orange',
  'Campa Lemon',
  'Appy Fizz',
  'Appy',
  'Frooti',
  'B Natural',
  'Real Juice',
  'Real Fruit Power',
  'Raw Pressery',
  'Paper Boat Aam Panna',
  'Paper Boat Jaljeera',
  'Paper Boat Chilli Guava',
  'Bisleri',
  'Bisleri Water',
  'Bisleri Soda',
  'Bailey Water',
  'Himalayan Water',
  'Vedica Water',
  'Bovonto',
  'Sosyo',
  'RimZim',
  'Soda',
  'Club Soda',
  'Tonic Water',
  'Mineral Water',
  'Sparkling Water',
  'Fresh Lime Soda',
  'Fresh Lime Water',
  'Lassi',
  'Sweet Lassi',
  'Salted Lassi',
  'Mango Lassi',
  'Buttermilk',
  'Masala Chaas',
  'Cold Coffee',
  'Iced Coffee',
  'Filter Coffee',
  'Cappuccino',
  'Latte',
  'Espresso',
  'Americano',
  'Tea',
  'Masala Tea',
  'Green Tea',
  'Lemon Tea',
  'Iced Tea',
  'Mango Juice',
  'Orange Juice',
  'Pineapple Juice',
  'Watermelon Juice',
  'Apple Juice',
  'Sugarcane Juice',
  'Mosambi Juice',
  'Mocktail',
  'Virgin Mojito',
  'Blue Lagoon',
  'Fruit Punch',
  'Milkshake',
  'Chocolate Shake',
  'Strawberry Shake',
  'Vanilla Shake',
  'Oreo Shake',
  'Mango Shake',
  'Badam Milk',
  'Jaljeera',
  'Kokum Sherbet',
  'Aam Panna',
  'Red Bull',
  'Red Bull Sugar Free',
  'Monster Energy',
  'Monster Ultra',
  'Paper Boat',
];

const desserts = [
  'Brownie',
  'Chocolate Brownie',
  'Walnut Brownie',
  'Ice Cream',
  'Vanilla Ice Cream',
  'Chocolate Ice Cream',
  'Strawberry Ice Cream',
  'Butterscotch Ice Cream',
  'Kulfi',
  'Malai Kulfi',
  'Mango Kulfi',
  'Gulab Jamun',
  'Kala Jamun',
  'Rasgulla',
  'Rasmalai',
  'Jalebi',
  'Rabri',
  'Kheer',
  'Phirni',
  'Gajar Halwa',
  'Moong Dal Halwa',
  'Sooji Halwa',
  'Basundi',
  'Shrikhand',
  'Payasam',
  'Mysore Pak',
  'Ladoo',
  'Motichoor Ladoo',
  'Kaju Katli',
  'Barfi',
  'Peda',
  'Sandesh',
  'Mishti Doi',
  'Cheesecake',
  'Chocolate Cake',
  'Black Forest Cake',
  'Red Velvet Cake',
  'Tiramisu',
  'Panna Cotta',
  'Waffle',
  'Pancake',
  'Donut',
  'Cupcake',
  'Pastry',
  'Apple Pie',
  'Sizzling Brownie',
  'Falooda',
  'Fruit Custard',
  'Caramel Custard',
  'Churros',
];

const alcohol = [
  'Beer',
  'Kingfisher Beer',
  'Kingfisher Premium',
  'Kingfisher Strong',
  'Kingfisher Ultra',
  'Kingfisher Ultra Max',
  'Kingfisher Ultra Witbier',
  'Kingfisher Storm',
  'Kingfisher Draught',
  'Heineken Silver',
  'Heineken 0.0',
  'Amstel Grande',
  'Budweiser',
  'Budweiser Magnum',
  'Heineken',
  'Corona',
  'Bira Blonde',
  'Bira White',
  'Tuborg',
  'Carlsberg',
  'Hoegaarden',
  'Guinness',
  'Draught Beer',
  'House Wine',
  'Red Wine',
  'White Wine',
  'Rose Wine',
  'Sula Wine',
  'Fratelli Wine',
  'Sparkling Wine',
  'Champagne',
  'Whisky',
  'Blenders Pride',
  'Royal Stag',
  'Signature Whisky',
  'Antiquity Blue',
  'Black Label',
  'Johnnie Walker',
  'Johnnie Walker Black Label',
  'Johnnie Walker Red Label',
  'Red Label',
  'Black Dog',
  'Black and White',
  'Black & White',
  'Vat 69',
  'Chivas Regal',
  'Jack Daniels',
  'Jameson',
  'Glenfiddich',
  'The Singleton',
  'McDowell No 1',
  "McDowell's No 1",
  'Royal Challenge',
  'Royal Challenge Whisky',
  'Epitome Reserve',
  'Godawan',
  'Vodka',
  'Smirnoff',
  'Absolut Vodka',
  'Grey Goose',
  'Ketel One',
  'Rum',
  'Old Monk',
  'Bacardi',
  'Captain Morgan',
  'Gin',
  'Gordons',
  "Gordon's",
  'Tanqueray',
  'Bombay Sapphire',
  'Greater Than',
  'Hapusa',
  'Beefeater',
  'Tequila',
  'Jose Cuervo',
  'Patron',
  'Don Julio',
  'Brandy',
  'Morpheus Brandy',
  'Cocktail',
  'Mojito',
  'Margarita',
  'Long Island Iced Tea',
  'Cosmopolitan',
  'Martini',
  'Daiquiri',
  'Bloody Mary',
  'Sangria',
  'Jagermeister',
  'Baileys',
  'Pipa Rum De Goa',
  'BroCode',
  'Soju',
];

function aliasFor(itemName) {
  const aliases = [];
  if (itemName.includes('Coca Cola') || itemName.includes('Coca-Cola')) aliases.push('Coke');
  if (itemName === '7 Up' || itemName === 'Seven Up') aliases.push('7up', 'Seven Up', '7 Up');
  if (itemName === 'Thums Up') aliases.push('Thumbs Up', 'Thumsup');
  if (itemName === 'McDowell No 1') aliases.push("McDowell's No 1", 'McDowells No 1');
  if (itemName === 'Black and White') aliases.push('Black & White');
  if (itemName === 'Gordons') aliases.push("Gordon's");
  if (itemName === 'BroCode') aliases.push('Bro Code');
  if (itemName.includes('Paneer')) aliases.push(itemName.replace('Paneer', 'Panner'));
  if (itemName.includes('Biryani')) aliases.push(itemName.replace('Biryani', 'B1ryani'));
  return aliases;
}

export const defaultMenuItems = [
  ...indianVeg.map((itemName) => ({ itemName, category: 'veg' })),
  ...indianNonVeg.map((itemName) => ({ itemName, category: 'nonveg' })),
  ...fastFoodVeg.map((itemName) => ({ itemName, category: 'veg' })),
  ...drinks.map((itemName) => ({ itemName, category: 'drink' })),
  ...desserts.map((itemName) => ({ itemName, category: 'dessert' })),
  ...alcohol.map((itemName) => ({ itemName, category: 'alcohol' })),
].map((entry) => ({
  ...entry,
  aliases: JSON.stringify(aliasFor(entry.itemName)),
}));
